// src/layout/Footer.tsx
import "./../static/styles/Footer.css";

export const Footer = () => {
    return (
        <div className="card">
            <div className="card-body">
                <p className="card-text footer text-center">
                    GitHub 2023 - Designed and implemented by @pawelNu
                </p>
            </div>
        </div>
    );
};

// src/lib/components/Footer.svelte
<script lang="ts">
</script>

<div class="uk-card uk-card-secondary p-5">
  <footer>
    <div class="uk-container uk-container-expand text-center">
      <ul class="uk-list">
        <li>© 2025 pawelNu</li>
        <li>
          <a
            href="https://github.com/pawelNu/frontend-project-manager"
            target="_blank"
            class="uk-link">Link to project on Github</a
          >
        </li>
        <li>
          Designed and implemented by <a
            href="https://github.com/pawelNu"
            target="_blank"
            class="uk-link">@pawelNu</a
          >
        </li>
      </ul>
    </div>
  </footer>
</div>
