// src/components/layout/Footer.tsx
export const Footer = () => {
    return (
        <div className="card">
            <div className="card-body">
                <div className="text-center d-flex flex-column row-gap-2">
                    <div>© 2025 pawelNu</div>
                    <div>
                        <a href="https://github.com/pawelNu/frontend-project-manager" target="_blank">
                            Link to project on Github
                        </a>
                    </div>
                    <div>
                        Designed and implemented by{' '}
                        <a href="https://github.com/pawelNu" target="_blank">
                            @pawelNu
                        </a>
                    </div>
                </div>
            </div>
        </div>
    );
};

{
    /* <div class="uk-card uk-card-secondary p-5">
  <footer>
    <div class="uk-container uk-container-expand text-center">
      <ul class="uk-list">
        <li>© 2025 pawelNu</li>
        <li>
          <a
            href="https://github.com/pawelNu/frontend-project-manager"
            target="_blank"
            class="uk-link">Link to project on Github</a
          >
        </li>
        <li>
          Designed and implemented by <a
            href="https://github.com/pawelNu"
            target="_blank"
            class="uk-link">@pawelNu</a
          >
        </li>
      </ul>
    </div>
  </footer>
</div> */
}

// src/lib/components/Footer.svelte
<script lang="ts">
</script>

<div class="uk-card uk-card-secondary p-5">
  <footer>
    <div class="uk-container uk-container-expand text-center">
      <ul class="uk-list">
        <li>© 2025 pawelNu</li>
        <li>
          <a
            href="https://github.com/pawelNu/frontend-project-manager"
            target="_blank"
            class="uk-link">Link to project on Github</a
          >
        </li>
        <li>
          Designed and implemented by <a
            href="https://github.com/pawelNu"
            target="_blank"
            class="uk-link">@pawelNu</a
          >
        </li>
      </ul>
    </div>
  </footer>
</div>
